# Generated by Django 3.2.8 on 2022-01-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubinfo',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
