# Generated by Django 3.2.8 on 2021-12-20 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField(default=datetime.datetime.today)),
                ('end_date', models.DateField(default=datetime.datetime.today)),
            ],
            options={
                'db_table': 'promotions',
                'ordering': ['-id'],
            },
        ),
    ]
