# Generated by Django 3.2.8 on 2021-12-28 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.CharField(blank=True, default='', max_length=255)),
                ('bookable', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(1, 'STAY '), (2, 'CELEBRATE '), (3, 'ENTERTAIN '), (4, 'DINE '), (5, 'SHOP '), (6, 'RELAX ')])),
            ],
            options={
                'db_table': 'services',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('open_time', models.TimeField(null=True)),
                ('close_date', models.TimeField(null=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'db_table': 'service_times',
                'ordering': ['-id'],
            },
        ),
    ]
