# Generated by Django 3.2.8 on 2021-12-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageService',
        ),
        migrations.AlterModelTable(
            name='imageservice',
            table='image_services',
        ),
    ]
