# Generated by Django 3.2.8 on 2022-01-05 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20211229_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_service', to='service.service'),
        ),
    ]
