# Generated by Django 3.2.8 on 2022-01-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_servicetime_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicetime',
            old_name='close_date',
            new_name='close_time',
        ),
    ]
