# Generated by Django 3.2.8 on 2022-01-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_rename_close_date_servicetime_close_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='has_menu',
            field=models.BooleanField(default=False),
        ),
    ]
