# Generated by Django 3.2.8 on 2022-01-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_service_has_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageservice',
            old_name='url',
            new_name='urlrelated_name',
        ),
        migrations.RemoveField(
            model_name='imageservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='imageservice',
            name='title',
        ),
        migrations.AlterField(
            model_name='service',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
