# Generated by Django 3.2.8 on 2022-01-08 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_rename_urlrelated_name_imageservice_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageservice',
            old_name='url',
            new_name='image_url',
        ),
    ]
