# Generated by Django 3.2.8 on 2022-01-09 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subservice', '0002_remove_subservicetype_service'),
        ('service', '0013_alter_service_subservice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='subservice_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='subservice.subservicetype'),
        ),
    ]
