# Generated by Django 3.2.8 on 2021-12-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=128)),
                ('gender', models.IntegerField(choices=[(2, 'Không xác định'), (0, 'Nữ'), (1, 'Nam')])),
            ],
            options={
                'db_table': 'staffs',
                'ordering': ['-user'],
            },
        ),
    ]
