# Generated by Django 3.2.8 on 2022-01-18 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_device'),
        ('notification', '0002_remove_notification_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='membership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='member.membershiptype'),
        ),
    ]
