# Generated by Django 3.2.8 on 2022-01-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20220119_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='body',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
    ]
