# Generated by Django 3.2.8 on 2022-01-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20220119_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.TextField(default='body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.TextField(default='title'),
            preserve_default=False,
        ),
    ]
