# Generated by Django 3.2.8 on 2022-01-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_notification_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='member',
        ),
    ]
