# Generated by Django 3.2.8 on 2021-12-29 15:40

from django.db import migrations, models
import django.db.models.deletion
import modules.event.event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20211229_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.CreateModel(
            name='ImageEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.ImageField(blank=True, null=True, upload_to=modules.event.event.models.upload_to)),
                ('title', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='event.event')),
            ],
            options={
                'db_table': 'image_events',
                'ordering': ['-id'],
            },
        ),
    ]
