# Generated by Django 3.2.8 on 2022-01-05 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20211229_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_event', to='event.event'),
        ),
    ]
