# Generated by Django 3.2.8 on 2022-01-08 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_imageevent_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageevent',
            old_name='url',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='imageevent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='imageevent',
            name='title',
        ),
    ]
