# Generated by Django 3.2.8 on 2022-01-15 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_device'),
        ('event', '0007_alter_event_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_member', to='member.member'),
        ),
    ]
