# Generated by Django 3.2.8 on 2022-01-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_eventmember_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='noti_status',
            field=models.IntegerField(blank=True, choices=[(0, 'NONE'), (1, '8 Days'), (2, '2 Days'), (3, 'Today')], null=True),
        ),
    ]
