# Generated by Django 3.2.8 on 2022-01-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_remove_eventmember_noti_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='email',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='member_name',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
    ]
