# Generated by Django 3.2.8 on 2021-12-27 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=128)),
                ('dob', models.DateField(null=True)),
                ('occupation', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('gender', models.IntegerField(choices=[(2, 'Không xác định'), (0, 'Nữ'), (1, 'Nam')])),
                ('type', models.IntegerField(choices=[(0, 'None'), (1, 'Member'), (2, 'Wellness member')])),
                ('register_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'members',
                'ordering': ['-user'],
            },
        ),
    ]
