# Generated by Django 3.2.8 on 2021-12-27 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='member',
            name='expire_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='member',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='member',
            name='register_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
