# Generated by Django 3.2.8 on 2022-01-05 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_imageservice_service'),
        ('member', '0004_auto_20211229_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilege', to='member.member')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilege', to='service.service')),
            ],
            options={
                'db_table': 'privileges',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='services',
            field=models.ManyToManyField(related_name='member', through='member.Privilege', to='service.Service'),
        ),
    ]
