# Generated by Django 3.2.8 on 2022-01-05 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_imageservice_service'),
        ('member', '0005_auto_20220105_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=225, unique=True)),
                ('services', models.ManyToManyField(related_name='membership_type', to='service.Service')),
            ],
            options={
                'db_table': 'membership_types',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='member',
            name='services',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='type',
        ),
        migrations.DeleteModel(
            name='Privilege',
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='member.membershiptype'),
        ),
    ]
