# Generated by Django 3.2.8 on 2022-01-05 12:55

from django.db import migrations, models
import modules.account.member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20220105_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=modules.account.member.models.upload_to),
        ),
    ]
