# Generated by Django 3.2.8 on 2022-01-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_member_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingservice',
            name='adult',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='check_in',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='check_out',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='children',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='email',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='member_name',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='participants',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='party_size',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
