# Generated by Django 3.2.8 on 2022-01-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_alter_bookingservice_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingservice',
            name='status',
        ),
    ]
