# Generated by Django 3.2.8 on 2022-01-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_service_subservice_type'),
        ('member', '0014_alter_bookingservice_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingservice',
            unique_together={('service', 'member')},
        ),
    ]
