# Generated by Django 3.2.8 on 2022-01-13 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_alter_bookingservice_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
