# Generated by Django 3.2.8 on 2022-01-13 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_populate_uid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
