# Generated by Django 3.2.8 on 2022-01-14 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_auto_20220113_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'IOS '), (1, 'ANDROID ')], null=True)),
                ('registration_token', models.CharField(max_length=225)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='member.member')),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['-id'],
            },
        ),
    ]
