# Generated by Django 3.2.8 on 2022-01-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingservice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
