# Generated by Django 3.2.8 on 2022-01-20 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_auto_20220120_1517'),
        ('member', '0021_alter_bookingservice_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_members', to='member.member')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_members', to='notification.notification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='member',
            name='notifications',
            field=models.ManyToManyField(related_name='members', through='member.NotificationMember', to='notification.Notification'),
        ),
    ]
