# Generated by Django 3.2.8 on 2022-01-20 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0023_auto_20220120_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingservice',
            old_name='children',
            new_name='childrenss',
        ),
    ]
