# Generated by Django 3.2.8 on 2022-01-20 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0024_rename_children_bookingservice_childrenss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingservice',
            old_name='childrenss',
            new_name='childs',
        ),
    ]
