# Generated by Django 3.2.8 on 2022-01-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0025_rename_childrenss_bookingservice_childs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='notifications',
        ),
    ]
