# Generated by Django 3.2.8 on 2022-01-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0026_remove_member_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationMember',
        ),
    ]
