# Generated by Django 3.2.8 on 2022-03-30 21:29

from tkinter.messagebox import NO
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0027_delete_notificationmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_remote_id',
            field=models.CharField(default=None, max_length=225, null=True),
        ),
    ]
