# Generated by Django 3.2.8 on 2022-03-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0028_member_member_remote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='full_name',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.IntegerField(choices=[(2, 'Không xác định'), (0, 'Nữ'), (1, 'Nam')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_remote_id',
            field=models.CharField(default=None, max_length=225, null=True, unique=True),
        ),
    ]
