# Generated by Django 3.2.8 on 2022-04-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0029_auto_20220330_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_remote_id',
            field=models.CharField(default=None, max_length=225, null=True),
        ),
    ]
