# Generated by Django 3.2.8 on 2022-04-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0031_remove_member_member_remote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_remote_id',
            field=models.CharField(default=None, max_length=225, null=True),
        ),
    ]
