# Generated by Django 3.2.8 on 2021-12-28 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'dish_categories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=225, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=225)),
                ('content', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('dish_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='dish.dishcategory')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='service.service')),
            ],
            options={
                'db_table': 'dishes',
                'ordering': ['-id'],
            },
        ),
    ]
