# Generated by Django 3.2.8 on 2021-12-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dishcategory',
            table='dish_category',
        ),
    ]
