# Generated by Django 3.2.8 on 2022-01-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_rename_close_date_servicetime_close_time'),
        ('dish', '0002_alter_dishcategory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcategory',
            name='service',
            field=models.ManyToManyField(related_name='dish_categories', through='dish.Dish', to='service.Service'),
        ),
    ]
