# Generated by Django 3.2.8 on 2022-01-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
