# Generated by Django 3.2.8 on 2022-01-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0002_auto_20220109_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='title',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
    ]
