# Generated by Django 3.2.8 on 2022-01-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0003_checkin_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='title',
        ),
    ]
