# Generated by Django 3.2.8 on 2022-01-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0004_remove_checkin_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='check_out',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
